cluster.name: cluster-production
node.name: es-data-01
node.master: false
node.data: false
network.host: 10.0.0.14
path.data: /var/lib/elasticsearch
path.logs: /var/log/elasticsearch
discovery.seed_hosts: ["10.0.0.11"]
cluster.initial_master_nodes: ["es-master"]