cluster.name: cluster-vagrant

node.name: es-master

node.master: true

network.host: [_local_, _site_]

path.data: /var/lib/elasticsearch
path.logs: /var/log/elasticsearch

discovery.seed_hosts: ["10.0.0.11"]
cluster.initial_master_nodes: ["es-master"]

node.data: false
node.ingest: false
node.ml: false
node.voting_only: false
